### ISSUE TITLE
Unable to update raw-http annotation from project.yml

### ISSUE THREAD

**Issue by niks3089** [nimbella/nimbella-cli#179]
I want to change the `raw-http` annotation for my action and when I tried this from `project.yml`, I wasn't able to update it. I am not sure if it's intentional. I was able to update it from `nim action update` thought. Here's a sample config from my project.yml: 

```
      - name: playground-run
        limits:
          timeout: 5000
        annotations:
          provide-api-key: true
          raw-http: true
```
