### ISSUE TITLE
nim project create xxx --config fails to deploy due to invalid key in project.yml

### ISSUE THREAD

**Issue by jthomas** [nimbella/nimbella-cli#48]
## steps to reproduce

```
$ nim project create project_from_config --config
$ nim project deploy project_from_config
Error: Invalid key 'package' found in 'action' clause in project.yml
```
Here is the created `project.yml` => 

```yml
targetNamespace: ''
cleanNamespace: false
bucket: {}
parameters: {}
packages:
  - name: default
    shared: false
    clean: false
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: hello
        clean: false
        binary: false
        main: ''
        runtime: 'nodejs:default'
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
        package: default
```

The last line (`package: default`) is causing the issue. The error is thrown from here: https://github.com/nimbella/nimbella-cli/blob/master/deployer/src/util.ts#L305

The sample config created comes from here: https://github.com/nimbella/nimbella-cli/blob/master/src/generator/project.ts#L130

**I'm assuming the `package: default` line is accidental and can be removed from the config template generation?** 
If so - I'll submit a PR. It'll be worth maybe adding a test for this command in future.
